// Auto-generated by openapi-typescript. Placeholder stub committed for initial compile; will be overwritten.
export type paths = {};
export type operations = {};
export type components = {
  schemas: {
    User: any;
    StakingPackage: any;
    Investment: any;
  };
};
